config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :pages

  get 'bio', to: 'pages#show', id:26
  get 'works', to: 'pages#show', id:49

  get 'calculate_importance', to: 'pages#calculate_importance'

  resources :posts

  get 'tagged', to: 'posts#tagged'
  get 'rss', to: 'posts#rss'

  get 'signup', to:'users#new'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :users
  root 'posts#index'
  match ':controller/:action/:id', via: [:get, :post]

end

app/models/page.rb
class Page < ActiveRecord::Base
  # attr_accessible :title, :content, :clouded, :importance
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Bootsy::Container
  # attr_accessible :title, :content, :author, :tags, :tag_list
  acts_as_taggable_on :tags
  #named_scope :by_post_date, :order => "created_at DESC" #for taggable søk
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
    validates_confirmation_of :password
    validates_presence_of :password

    before_save :encrypt_password

    def encrypt_password
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end

    def self.authenticate(email, password)
      user = User.where(email: email).first
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_filter :tagcloud
  include Authentication
  helper :all # include all helpers, all the time

  protect_from_forgery with: :exception

  def tagcloud
    #find all pages for tag cloud
    #@tagpages=Page.find_all_by_clouded(true,:order => "title ASC")
    #@tagpages=Page.all_by_clouded(true,:order => "title ASC")
    @tagpages=Page.all.where(clouded:true).order("title ASC")
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :login_required, :except => [:show]
  before_filter :tagcloud

  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
    posst=Post.tagged_with(@page.title)
    @posts=posst.sort_by { |k| k['created_at'] }
    @posts.reverse!
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      flash[:notice] = "Successfully created page."
      redirect_to calculate_importance_path
    else
      render :action => 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(page_params)
      flash[:notice] = "Successfully updated page."
      redirect_to @page
    else
      render :action => 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "Successfully destroyed page."
    redirect_to pages_url
  end

  def calculate_importance
    @pages=Page.all
    hier=Array.new #lag sortert hierarki
    @pages.each_with_index do |p,i|
      posts=Post.tagged_with(p.title)

      ex1=0
      posts.each do |po|
        if po.created_at>700.days.ago
          ex1=+1 #addup bonus for last 2 year posts
        end
      end

      ex2=0
      posts.each do |po|
        if po.created_at>165.days.ago
          ex2=+1 #addup bonus for last halfyear posts
        end
      end

      ex3=0
      posts.each do |po|
        if po.created_at>30.days.ago
          ex3=+1 #addup bonus for last month posts
        end
      end

      ekstralengde=posts.length+ex1+ex2+ex3

      hier[i]=[p,ekstralengde] #lagre array med post og antall tags
    end
    sorted = hier.sort_by {|post,length| length} #sorter etter lengde
    sorted = sorted.reverse
    sorted.each_with_index do |p,i|
      if i>10
        p[0].importance=10 #stopp på 10 - minste størrelse
      else
        p[0].importance=i #antall poster knytta til page avgjør basis for importance
      end
      p[0].save #oppdater
    end

    redirect_to root_url
  end

private
  def page_params
    params.require(:page).permit(:title, :content, :clouded, :importance)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :login_required, :except => [:index, :show, :tagged, :rss]
  before_filter :tagcloud
  layout "application", :except => :rss

  def index
    @posts = Post.all.paginate(page: params[:page], per_page: 15).order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
  end

  def tagged
    @posts=Post.tagged_with(params[:tagg]).paginate(:page => params[:page], :per_page => 8)
    render :action => 'index'
  end

  def rss
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Successfully created post."
      redirect_to calculate_importance_path
    else
      render :action => 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post."
      redirect_to @post
    else
      render :action => 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Successfully destroyed post."
    redirect_to posts_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :contentlong, :author, :tag_list, :bootsy_image_gallery_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def update
  end

  def destroy
  end

  def new
    @user = User.new
  end

  def edit
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_pages_navbar.html.erb
<div id="main_navbar">


		<p id="cloud">

		<% @tagpages.each_with_index do |t,i|%>

		<%if i & 1 == 1%>
		<span class="odd">
		<%= link_to t.title, page_path(t.id), :class => "tag#{t.importance}" %>
		</span>
		<%else%>
		<span class="even">
		<%= link_to t.title, page_path(t.id), :class => "tag#{t.importance}" %>
		</span>
		<%end%>
		<%end%>
		</p>



</div>

app/views/layouts/application.html kopi.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogandpages4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>Eyes on your instruments</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
 <script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-4586950-3']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="../" class="navbar-brand">Espen Sommer Eide</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="../">news</a>
            </li>
            <li>
              <a href="../works">works</a>
            </li>
            <li>
              <a href="../bio">bio</a>
            </li>
            <li>
              <a href="../rss">rss</a>
            </li>

          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="login">login <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="login">

                <li><%= link_to "Log in", log_in_path %></li>
                <% if logged_in? %>
                <li><%= link_to "Log out", log_out_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Pages", pages_path %></li>
                <li class="divider"></li>
                <li><%= link_to "New user", signup_path %></li>
                <li><%= link_to "New page", new_page_path %></li>
                <li><%= link_to "New Post", new_post_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Update_cloud", calculate_importance_path %></li>
                <% end %>
              </ul>
            </li>

          </ul>

        </div>
      </div>
    </div>

    <div class="container">

      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12">

            <%= render :partial => 'layouts/pages_navbar'%>

          </div>


        </div>

      </div>

      <div class="headerpadding">
		    <%- flash.each do |name, msg| -%>
	        <%= content_tag :div, msg, :id => "flash_#{name}" %>
	      <%- end -%>
			</div>

      <div class="bs-docs-section">
        <div class="row">

                <%= yield %>

        </div>
      </div>



      <div id="copyright">
		    <p>ESPEN SOMMER EIDE &copy;
			<%=Time.now.strftime("%Y")%></p>
		  </div> <!-- END COPYRIGHT -->
			</div>




    </div>




  </body>
</html>

app/views/layouts/application.htmlOLD.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogandpages4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/applicationolder.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>Eyes on your instruments</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

 <script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-4586950-3']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="../" class="navbar-brand">Espen Sommer Eide</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="../">news</a>
            </li>
            <li>
              <a href="../works">works</a>
            </li>
            <li>
              <a href="../bio">bio</a>
            </li>
            <li>
              <a href="../rss">rss</a>
            </li>

          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="login">login <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="login">

                <li><%= link_to "Log in", log_in_path %></li>
                <% if logged_in? %>
                <li><%= link_to "Log out", log_out_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Pages", pages_path %></li>
                <li class="divider"></li>
                <li><%= link_to "New user", signup_path %></li>
                <li><%= link_to "New page", new_page_path %></li>
                <li><%= link_to "New Post", new_post_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Update_cloud", calculate_importance_path %></li>
                <% end %>
              </ul>
            </li>

          </ul>

        </div>
      </div>
    </div>

    <div id="container">

			<div id="content" class="clear">

			<div id="thinheader" class="">
			  <h1 class="logo"><a href="/" title="news"><span>news</span></a></h1>

			  <div id="session_nav">

					<ul>
			  <li><%= link_to "News", root_path %></li><li><span class="separator">|
				</span><%= link_to "Works", "/works" %></li><li><span class="separator">|</span>
				<%= link_to "Bio", "/bio" %></li><li><span class="separator">|</span>
				</span><%= link_to "RSS", "/rss" %></li>

						<% if logged_in? %>
							<li><span class="separator">|</span><%= link_to "Pages", pages_path %><span class="separator">|</span>
							<%= link_to "New user", signup_path %><span class="separator">|</span>
							<%= link_to "New page", new_page_path %><span class="separator">|</span>
							<%= link_to "New Post", new_post_path %><span class="separator">|</span>
							<%= link_to "Update_cloud", calculate_importance_path %><span class="separator">|</span>
			        <%= link_to "Log out", log_out_path %></li>
			      <% end %>

			</ul>
			  </div> <!-- END TOPNAV -->

			</div> <!-- END HEADER -->
			<div id="caption">by espen sommer eide</div>

			<div class="headerpadding">
		    <%- flash.each do |name, msg| -%>
	        <%= content_tag :div, msg, :id => "flash_#{name}" %>
	      <%- end -%>
			</div>

			<%= render :partial => 'layouts/pages_navbar'%>

			</div>

      <%= yield %>
			<br>

    </div>
		<div id="footer" class="clear clearfix">

		  <div class="copyright">
		    <p>ESPEN SOMMER EIDE &copy;
			<%=Time.now.strftime("%Y")%> | </p>
		  </div> <!-- END COPYRIGHT -->

		</div> <!-- END FOOTER -->

  </body>
</html>

app/views/layouts/pages/show.html.erb
<div id="entriespage">
	
<p>

<div id="page_title"><h2><%=@page.title%></h2></div>
<div id="page_content"><%= @page.content %></div>
</p>
<p>
<% if logged_in? %>
  <%= link_to "Edit", edit_page_path(@page) %> |
  <%= link_to "Destroy", @page, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", pages_path %>
<%end%>

</p>
</div><div class="entriespadding">
 
</div>

<div id="entries">
  <% for post in @posts %>
			<div class="dateheader"><h3 class="entrydate"><span><%= post.created_at.strftime("%d") %></span><%= post.created_at.strftime("%B%Y") %></h3></div>
    
      <div id="post_title"><h4><%= link_to post.title, post %></h4></div>    
		
    
			<div id="post_content"><%= post.content %></div>
		
			<div id="time_and_author">Tags: 
			<%post.tags.each do |t|%>
			<%= link_to t, tagged_path(:tagg=>t.to_s)%>
			<%end%>
			</div>
		
		
		<% if logged_in? %>
		
	<div id="loggedin">		
			<%= link_to "Show", post %>
			 |
	      <%= link_to "Edit", edit_post_path(post) %> |
				<%= link_to "Destroy", post, :confirm => 'Are you sure?', :method => :delete %>	
			</div>
		
		<%end%>
		<br>
  <% end %>
<br>


	

</div>
&nbsp;

app/views/layouts/posts/_form.html.erb
<% form_for @post do |f| %>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br />

  </p>
  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

<br><br><br><br><br><br>
Alternativ form:

<% form_for @post do |f| %>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/layouts/posts/index.html.erb
<div id="entries">


  <% for post in @posts %>
			<div class="dateheader"><h3 class="entrydate"><span><%= post.created_at.strftime("%d") %></span><%= post.created_at.strftime("%B%Y") %></h3></div>

      <div id="post_title"><h4><%= link_to post.title, post %></h4></div>


			<div id="post_content"><%= post.content %></div>

			<div id="time_and_author">Tags:
			<%post.tags.each do |t|%>
			<%= link_to t, tagged_path(:tagg=>t.to_s)%>
			<%end%>
			</div>


		<% if logged_in? %>

	<div id="loggedin">
			<%= link_to "Show", post %>
			 |
	      <%= link_to "Edit", edit_post_path(post) %> |
				<%= link_to "Destroy", post, :confirm => 'Are you sure?', :method => :delete %>
			</div>

		<%end%>
		<br>
  <% end %>
<br>

	<div id="post_content"><br><br>
	<%= will_paginate @posts %>
	</div>
</div>

&nbsp;

app/views/layouts/posts/new.html.erb
<div id="editform">
    <div id="form_content">
<h4>Edit post</h4>

				<%= render :partial => 'form' %>
<p><%= link_to "Back to List", posts_path %></p>
</div>

</div>

app/views/pages/_form.html.erb
<p><%= form_for @page do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, size:40 %><br>
	  <%= f.label :importance %>
	  <%= f.text_field :importance, size: 5 %><br>
		<%= f.label :clouded %>
	  <%= f.select(:clouded, [["Yes",true],["No",false]]) %><br>
    <%= f.label :content %>
    <%= f.bootsy_area :content, size: "100x30", editor_options: { html: true} %><br>
		<%= f.submit "Submit" %>
<% end %></p>



<p>for VIMEO and youtube embed, put ifram in div with class = myIframe
</p>

app/views/pages/edit.html.erb
<div class="col-lg-12 col-md-12 col-sm-12">
	<div class="bs-component">

<p>
<%= render :partial => 'form' %>
</p>
<p>
  <%= link_to "Show", @page %> |
  <%= link_to "View All", pages_path %>
</p>

</div>
</div>

app/views/pages/index.html.erb
<% title "pages" %>
<div class="col-lg-6 col-md-8 col-sm-9">
<table>
  <% for page in @pages %>
  <tr>
    <td><div id="post_title"><%= link_to page.title, page %></div></td>
	</tr>
	<tr>
		<td><div id="time_and_author"><%= page.created_at %></div></td>
	</tr>
			<td><%= link_to "Show", page %>
			<% if logged_in? %> |
	      <%= link_to "Edit", edit_page_path(page) %> |
<%= link_to "Destroy", page, :confirm => 'Are you sure?', :method => :delete %>
			<%end%><td>
		</tr>
		<tr><td><br></td></tr>
  <% end %>
</table>
<% if logged_in? %>
	<p><%= link_to "New page", new_page_path %></p>
<%end%>

</div>
&nbsp;

app/views/pages/new.html.erb
<div class="col-lg-12 col-md-12 col-sm-12">
	<div class="bs-component">


<%= render :partial => 'form' %>

<p>
<%= link_to "Back to List", pages_path %>
</p>

</div>
</div>

app/views/pages/show.html.erb
<div class="col-lg-12 col-md-12 col-sm-12">
<div class="im-centered">
<p>
<div id="page_title"><h2><%=@page.title%></h2></div>
<div id="page_content"><%=raw @page.content %></div>
</p>
<p>
<% if logged_in? %>
  <%= link_to "Edit", edit_page_path(@page) %> |
  <%= link_to "Destroy", @page, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", pages_path %>
<%end%>
</p>
</div>

<% for post in @posts %>
<div class="im-centered">
<h3 class="entrydate"><%= post.created_at.strftime("%d") %><%= post.created_at.strftime("%B%Y") %>
<%= link_to post.title, post %></h3>
<%=raw post.content %>
<%=raw post.contentlong %>
</div><div class="im-centered">
<div id="time_and_author">Tags:
<%post.tags.each do |t|%>
<%= link_to t, tagged_path(:tagg=>t.to_s)%>
<%end%>
</div></div>
<div class="im-centered">

		<% if logged_in? %>

	<div id="loggedin">
			<%= link_to "Show", post %>
			 |
	      <%= link_to "Edit", edit_post_path(post) %> |
				<%= link_to "Destroy", post, :confirm => 'Are you sure?', :method => :delete %>
			</div>

		<%end%>
		<br>
</div>

<% end %>
<br>



</div>

&nbsp;

app/views/posts/_form.html.erb
<p><%= form_for @post do |f| %>
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %><br>
    <%= f.label :author %>
    <%= f.text_field :author %><br>
    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :content %>
    <%= f.bootsy_area :content, size: "100x30", editor_options: { html: true} %><br>
    <%= f.label :contentlong %>
    <%= f.bootsy_area :contentlong, size: "100x30", editor_options: { html: true} %><br>
    <%= f.submit "Submit" %>
<% end %></p>

<p>for VIMEO and youtube embed, put ifram in div with class = myIframe
</p>

app/views/posts/edit.html.erb
<div class="col-lg-12 col-md-12 col-sm-12">
	<div class="bs-component">

<p>
<%= render :partial => 'form' %>
</p>
<p>
  <%= link_to "Show", @post %> |
  <%= link_to "View All", posts_path %>
</p>

</div>
</div>

app/views/posts/index.html.erb
<% @posts.each_with_index do |post, index| %>
<% if index==9 %>
<div class="col-lg-6 col-md-6 col-sm-9">
  <div class="bs-component">
    <h3>Tweets</h3>
    <a class="twitter-timeline"  width="auto" href="https://twitter.com/esomm" data-widget-id="675077698843254784" data-chrome="nofooter noborders noheader">Tweets by @esomm</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div>
</div>
<%end%>
<div class="col-lg-6 col-md-6 col-sm-9">
  <div class="bs-component">
    <h3><%= post.created_at.strftime("%d") %><%= post.created_at.strftime("%B%Y") %>
        <%= link_to post.title, post %></h3>
        <%=raw post.content %>
        <% if post.contentlong.blank? == false %>
        <p><%= link_to 'read more – link to full post', post %></p>
        <%end%>
		<div id="time_and_author">Tags:
		<%post.tags.each do |t|%>
		  <%= link_to t, tagged_path(:tagg=>t.to_s)%>
		<%end%>
		</div>

	<% if logged_in? %>

    <div id="loggedin">
		<%= link_to "Show", post %>
		 |
      <%= link_to "Edit", edit_post_path(post) %> |
			<%= link_to "Destroy", post, :confirm => 'Are you sure?', :method => :delete %>
		</div>

	<%end%>
	<br>
</div>
</div>
<% end %>

<br>
<div class="col-lg-12 col-md-12 col-sm-12">

<div id="post_content"><br><br>
<%= will_paginate @posts %>
</div>
</div>

app/views/posts/new.html.erb
<div class="col-lg-12 col-md-12 col-sm-12">
	<div class="bs-component">

<p>
<%= render :partial => 'form' %>
</p>
<p>
<%= link_to "Back to List", posts_path %>
</p>

</div>
</div>

app/views/posts/show.html.erb
<div class="col-lg-12 col-md-12 col-sm-12">
<div class="im-centered">
<h3 class="entrydate"><%= @post.created_at.strftime("%d") %><%= @post.created_at.strftime("%B%Y") %>
		<%= link_to @post.title, @post %></h3>
			<%=raw @post.content %>
</div><div class="im-centered">			
			<%=raw @post.contentlong %>
</div><div class="im-centered">
			Tags:
			<%@post.tags.each do |t|%>
			<%= link_to t, tagged_path(:tagg=>t.to_s)%>
			<%end%><br>
</div><div class="im-centered">
			<p>
			<% if logged_in? %>
			  <%= link_to "Edit", edit_post_path(@post) %> |
			  <%= link_to "Destroy", @post, :confirm => 'Are you sure?', :method => :delete %> |
			<%end%>
			  <%= link_to "Back to blog", posts_path %>
			</p>
</div>
&nbsp;

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%=form_for @user do |f| %>
  <%=f.label :email %>
  <%=f.text_field :email %>
  <%=f.label :password %>
  <%=f.password_field :password %>
  <%=f.label :password_confirmation %>
  <%=f.password_field :password_confirmation %>
  <%=f.submit "Sign Up" %>
<%end%>